**Para um neuronio:**

In [ ]:
inputs = [1.2,3.4,5.3,1.7]
weights = [3.1,5.4,2.3,3.9]
bias = 2
output = inputs[0]*weights[0] + inputs[1]*weights[1] +  inputs[2]*weights[2] +  inputs[3]*weights[3]  + bias
print(output)

42.9


**Para uma camada:**

In [ ]:
inputs = [1.2,3.4,5.3,1.7]
weights1 = [3.1,5.4,2.3,3.9]
weights2 = [2.1,5.2,6.3,2.9]
weights3 = [5.1,2.2,2.3,5.9]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [ ]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] +  inputs[2]*weights1[2] +  inputs[3]*weights1[3]  + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] +  inputs[2]*weights2[2] +  inputs[3]*weights2[3]  + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] +  inputs[2]*weights3[2] +  inputs[3]*weights3[3]  + bias3]
print(output)

[42.9, 61.52, 36.32]


**refatorando e usando numpy..**

In [ ]:
import numpy as np 

inputs = [1.2,3.4,5.3,1.7]
weights = [[3.1,5.4,2.3,3.9],
           [2.1,5.2,6.3,2.9],
           [5.1,2.2,2.3,5.9]]
biases = [2,3,0.5]

output = np.dot(weights,inputs) + biases
print(output)

[42.9  61.52 36.32]


**Usando batches...**

In [ ]:
inputs = [ [1.2,3.4,5.3,1.7],
           [2.3,4.1,3.2,4.7],
           [3.5,3.4,1.6,2.6] ]

weights = [ [3.1,5.4,2.3,3.9],
            [2.1,5.2,6.3,2.9],
            [5.1,2.2,2.3,5.9] ]

biases = [2,3,0.5]

layer1_outputs = np.dot(inputs,np.array(weights).T) + biases
print(layer1_outputs)


[[42.9  61.52 36.32]
 [56.96 62.94 56.34]
 [45.03 45.65 44.85]]


**Segunda camada**

In [ ]:
weights2 = [ [2.1,1.4,6.3],
            [2.1,5.2,4.3],
            [5.1,1.2,3.3] ]

biases2 = [-1,2,0.5]

layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases2
print(layer2_outputs)

[[404.034 568.17  412.97 ]
 [561.674 691.166 552.446]
 [440.028 526.798 432.938]]


**Código Final**

In [ ]:
X = [ [1.2,3.4,5.3,1.7],     #boa pratica declarar os dados de input como X
      [2.3,4.1,3.2,4.7],
      [3.5,3.4,1.6,2.6] ]

class Layer_Dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases


layer1 = Layer_Dense(4,3)

layer1.forward(X)

print(layer1.output)

[[ 1.0320994  -1.01051023 -1.27112894]
 [ 1.10601984 -1.18281912 -0.74607193]
 [ 0.3548513  -0.9654725   0.07917222]]


**projeto**

In [ ]:

class Layer_Dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

#importando dataset
previsores = [0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5]

layer1 = Layer_Dense(30,16)
layer2 = Layer_Dense(16,16)
layer3 = Layer_Dense(16,1)

layer1.forward(previsores)
layer2.forward(layer1.output)
layer3.forward(layer2.output)

print(layer3.output)


[[-0.01545148]]


**Estudando activation functions**

In [ ]:
!pip install nnfs

**ReLU**

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X = [[1,2,3,2.5],
     [2.0,5.0, -1.0, 2.0],
     [-1.5,2.7,3.3,-0.8]]

X, y = spiral_data(100,3)

class Layer_Dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0,inputs)

layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)
activation1.forward(layer1.output)
print(activation1.output)


**Softmax**

In [ ]:
import math

layer_outputs = [4.8,1.21,2.385]

E = math.e

exp_values = []

for output in layer_outputs:
  exp_values.append(E**output)

print(exp_values)

norm_base = sum(exp_values)
norm_values = []

for value in exp_values:
  norm_values.append (value / norm_base)


In [ ]:
import math
import numpy as np

layer_outputs = [4.8,1.21,2.385]

E = math.e

exp_values = np.exp(layer_outputs)
norm_values = exp_values / np.sum(exp_values)

print(norm_values)


In [ ]:
import numpy as np

layer_outputs = [[4.8,1.21,2.385],
                 [9.9,-1.81,0.2],
                 [1.41,1.051,0.026]]

exp_values = np.exp(layer_outputs)
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)

print(norm_values)

