**Desenho**
https://jamboard.google.com/d/1YB1yVx4cyOIZlgti0TRcOto0q1dR41E2Ax213hu1DAc/edit?usp=sharing

**Para um neuronio:**

In [ ]:
inputs = [1.2,3.4,5.3,1.7]
weights = [3.1,5.4,2.3,3.9]
bias = 2
output = inputs[0]*weights[0] + inputs[1]*weights[1] +  inputs[2]*weights[2] +  inputs[3]*weights[3]  + bias   #aquele calculo padrao de inputs*weights + bias
print(output)

42.9


**Para uma camada:**

In [ ]:
import numpy as np 

inputs = [1.2,3.4,5.3,1.7]
weights = [[3.1,5.4,2.3,3.9],
           [2.1,5.2,6.3,2.9],
           [5.1,2.2,2.3,5.9]]
biases = [2,3,0.5]

output = np.dot(weights,inputs) + biases      #essa função do numpy simplifica aquilo q agnt fez em cima
print(output)

[42.9  61.52 36.32]


**Refatorando e usando numpy..**

In [ ]:
inputs = [1.2,3.4,5.3,1.7]
weights1 = [3.1,5.4,2.3,3.9]
weights2 = [2.1,5.2,6.3,2.9]
weights3 = [5.1,2.2,2.3,5.9]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [ ]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] +  inputs[2]*weights1[2] +  inputs[3]*weights1[3]  + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] +  inputs[2]*weights2[2] +  inputs[3]*weights2[3]  + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] +  inputs[2]*weights3[2] +  inputs[3]*weights3[3]  + bias3]
print(output)

**Usando batches...**

In [ ]:
inputs = [ [1.2,3.4,5.3,1.7],           #diferente da forma do input q agnt usou em cima, oq realmente acontece é q os inputs
           [2.3,4.1,3.2,4.7],           #são passados em batches(pacotes) ent agnt usou arrays dentro de arrays
           [3.5,3.4,1.6,2.6] ]          #o pq de usar batches é explicado na animação no minuto 5:13 do video de batches naquela playlist

weights = [ [3.1,5.4,2.3,3.9],
            [2.1,5.2,6.3,2.9],
            [5.1,2.2,2.3,5.9] ]

biases = [2,3,0.5]

layer1_outputs = np.dot(inputs,np.array(weights).T) + biases      #o metodo .T do numpy faz a transposta automaticamente.
print(layer1_outputs)                                             #agnt precisa da transporta pra poder fazer a mult matricial sem dar problema de shape


**Segunda camada**

In [ ]:
weights2 = [ [2.1,1.4,6.3],
            [2.1,5.2,4.3],                                            #aqui agnt faz o msm esquema, dessa vez pra segunda camada
            [5.1,1.2,3.3] ]

biases2 = [-1,2,0.5]

layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases2         #o output da camada anterior é usado pra multiplicar cm os pesos dessa
print(layer2_outputs)

**Código Final**

In [1]:
import numpy as np

X = [ [1.2,3.4,5.3,1.7],     #boa pratica declarar os dados de input como X
      [2.3,4.1,3.2,4.7],
      [3.5,3.4,1.6,2.6] ]

class Layer_Dense:
  def __init__(self, n_inputs,n_neurons):    #recebe como parametro o numero de inputs(nº de neuronios na camada anterior) e o nº de neuronios nessa camada que está sendo criada
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)  #é criada de forma aleatória uma matriz e multiplica por 0.1 para diminuir o tamanho dos dados
    self.biases = np.zeros((1, n_neurons))                      #é criado um array pros biases, inicialmente só tem 0
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases    #nesse método é feito aquele calculo de inputs * weights + bias

layer1 = Layer_Dense(4,3)        #aqui é usado a classe pra criar uma camada

layer1.forward(X)               

print(layer1.output)

[[ 0.05172401  0.45996612 -0.66795086]
 [-0.34974809  0.313758   -0.2388184 ]
 [ 0.0080852   0.23930502 -0.30663959]]


**Aplicando no projeto**

In [ ]:
#mesma classe q agnt criou acima
class Layer_Dense:         
  def __init__(self, n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

#No nosso projeto agnt precisa de 30 dados de entrada(textura,concavidade, etc). Aqui eu passei 30 dados de exemplo só pra agnt testar.
previsores = [0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,
              0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5,0.01,0.02,0.1,-0.3,0.5]

layer1 = Layer_Dense(30,16)   #a rede tem 30 entradas, entao a primeira camada tem um input de 30. A camada em si tem 16 neuronios
layer2 = Layer_Dense(16,16)
layer3 = Layer_Dense(16,1)

layer1.forward(previsores)
layer2.forward(layer1.output)
layer3.forward(layer2.output)

print(layer3.output)


[[-0.01545148]]
